### ISSUE TITLE
Extending Package

### ISSUE THREAD

**Issue by dannyrb** [slashdotdash/faker-cs#15]
Currently, is there any way to add additional Faker data/methods? For example, can I do something like:

```
using System;
using System.Collections.Generic;
using Faker.Extensions;

namespace Faker
{
    public static class PartNumber
    {
        public static string Full()
        {
            return ArrayExtensions.Random(Faker.Resources.PartNumber).Trim();
        }
    }
}
```

To add functionality to the existing implementation (installed via NuGet)

**Comment by VictorioBerra** [comment]
Came here to ask this too.

I think your best bet is to clone this project and add a new class and Resources file. Although, if you want something like a PartNumber you might be better off using AutoFixture.
